import type { Product, CategoryInfo } from "./types";

export const categories: CategoryInfo[] = [
  {
    id: "boiler",
    name: "Boilers",
    description: "Gas & oil boiler installation with next-day fitting available",
    icon: "Flame",
    color: "#ef4444",
    startingFrom: 1595,
  },
  {
    id: "heatpump",
    name: "Heat Pumps",
    description: "Air source heat pump installation with the £7,500 BUS grant handled for you",
    icon: "Thermometer",
    color: "#1C834B",
    startingFrom: 2999,
  },
];

export const sampleProducts: Product[] = [
  // ── BOILERS ─────────────────────────────────────────────
  {
    id: "boiler-1",
    name: "NCB 700 28kW",
    brand: "Navien",
    category: "boiler",
    type: "combi",
    description: "Reliable and affordable combi boiler with stainless steel heat exchanger. Great value for money with a compact, lightweight design.",
    imageUrl: null,
    basePrice: 1595,
    efficiency: "92%",
    warranty: 5,
    kw: 28,
    features: ["Stainless steel exchanger", "Lightweight design", "Affordable", "Quick installation"],
    popular: false,
  },
  {
    id: "boiler-2",
    name: "EcoTec Plus 830i",
    brand: "Vaillant",
    category: "boiler",
    type: "combi",
    description: "High-efficiency combi boiler perfect for small to medium homes. Compact design with built-in weather compensation for maximum savings.",
    imageUrl: null,
    basePrice: 1795,
    efficiency: "94%",
    warranty: 5,
    kw: 28,
    features: ["Compact design", "Weather compensation", "Low NOx emissions", "Easy to maintain"],
    popular: false,
  },
  {
    id: "boiler-3",
    name: "Logic Max Combi C35",
    brand: "Ideal",
    category: "boiler",
    type: "combi",
    description: "Powerful combi boiler ideal for larger homes with multiple bathrooms. Excellent hot water flow rate and built-in frost protection.",
    imageUrl: null,
    basePrice: 1999,
    efficiency: "93%",
    warranty: 7,
    kw: 35,
    features: ["High flow rate", "Built-in frost protection", "Easy install", "Compact footprint"],
    popular: false,
  },
  {
    id: "boiler-4",
    name: "Greenstar 8000 Life",
    brand: "Worcester Bosch",
    category: "boiler",
    type: "combi",
    description: "Premium combi boiler with top-of-the-range efficiency and a sleek modern design. Smart thermostat compatible with ultra-quiet operation.",
    imageUrl: null,
    basePrice: 2299,
    efficiency: "94%",
    warranty: 10,
    kw: 30,
    features: ["Smart thermostat ready", "10-year warranty", "Ultra-quiet operation", "Hydrogen blend ready"],
    popular: true,
  },
  {
    id: "boiler-5",
    name: "EcoTec Exclusive 843",
    brand: "Vaillant",
    category: "boiler",
    type: "combi",
    description: "Top-tier premium boiler with Green iQ technology. Maximum efficiency with smart connectivity built in and remote diagnostics.",
    imageUrl: null,
    basePrice: 2799,
    efficiency: "98%",
    warranty: 12,
    kw: 43,
    features: ["Green iQ technology", "12-year warranty", "Remote diagnostics", "Maximum efficiency"],
    popular: true,
  },
  {
    id: "boiler-6",
    name: "Greenstar 8000 Life System",
    brand: "Worcester Bosch",
    category: "boiler",
    type: "system",
    description: "Premium system boiler for homes with a hot water cylinder. Perfect for larger households with high hot water demand.",
    imageUrl: null,
    basePrice: 2199,
    efficiency: "94%",
    warranty: 10,
    kw: 30,
    features: ["System boiler", "10-year warranty", "High output", "Smart compatible"],
    popular: false,
  },

  // ── HEAT PUMPS (for upsell — range of sizes) ─────────────
  {
    id: "heatpump-1",
    name: "Arotherm Plus 5kW",
    brand: "Vaillant",
    category: "heatpump",
    type: "air-source",
    description: "Compact air source heat pump ideal for well-insulated flats and small homes. Natural R290 refrigerant with ultra-quiet operation.",
    imageUrl: null,
    basePrice: 6499,
    efficiency: "A+++",
    warranty: 7,
    kw: 5,
    features: ["£7,500 BUS grant eligible", "Natural R290 refrigerant", "Ultra quiet (35dB)", "Smart controls"],
    popular: false,
  },
  {
    id: "heatpump-2",
    name: "Arotherm Plus 7kW",
    brand: "Vaillant",
    category: "heatpump",
    type: "air-source",
    description: "Mid-range air source heat pump with natural refrigerant. Perfect for 2-3 bedroom homes. Eligible for the £7,500 BUS grant.",
    imageUrl: null,
    basePrice: 7999,
    efficiency: "A+++",
    warranty: 7,
    kw: 7,
    features: ["£7,500 BUS grant eligible", "Natural R290 refrigerant", "Ultra quiet", "Smart controls"],
    popular: false,
  },
  {
    id: "heatpump-3",
    name: "Vitocal 150-A 9kW",
    brand: "Viessmann",
    category: "heatpump",
    type: "air-source",
    description: "Premium 9kW air source heat pump with exceptional COP of 5.0. Ideal for 3-4 bedroom homes with radiators or underfloor heating.",
    imageUrl: null,
    basePrice: 9499,
    efficiency: "A+++",
    warranty: 10,
    kw: 9,
    features: ["COP 5.0", "£7,500 BUS grant eligible", "Underfloor compatible", "10-year warranty"],
    popular: true,
  },
  {
    id: "heatpump-4",
    name: "Vitocal 150-A 12kW",
    brand: "Viessmann",
    category: "heatpump",
    type: "air-source",
    description: "High-output 12kW heat pump for larger detached homes. Handles high heat demand with dual-zone control and weather compensation.",
    imageUrl: null,
    basePrice: 11499,
    efficiency: "A+++",
    warranty: 10,
    kw: 12,
    features: ["12kW output", "£7,500 BUS grant eligible", "Dual-zone control", "Weather compensation"],
    popular: false,
  },
  {
    id: "heatpump-5",
    name: "Daikin Altherma 3 16kW",
    brand: "Daikin",
    category: "heatpump",
    type: "air-source",
    description: "Top-of-range 16kW heat pump for large period properties and high heat-loss homes. Built-in backup heater for extreme cold snaps.",
    imageUrl: null,
    basePrice: 13999,
    efficiency: "A+++",
    warranty: 5,
    kw: 16,
    features: ["16kW output", "£7,500 BUS grant eligible", "Built-in backup heater", "Heating + cooling"],
    popular: false,
  },
];

export function getProductsByCategory(category: string): Product[] {
  return sampleProducts.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return sampleProducts.find((p) => p.id === id);
}

export function getHeatPumpProducts(): Product[] {
  return sampleProducts.filter((p) => p.category === "heatpump");
}
